services:
  app: 
    image: auth:1.0
    container_name: auth-app
    networks:
      - auth-bridge-network
    ports:
      - 8000:8000
    env_file:
      - .env

  celery-worker:
    image: auth:1.0
    container_name: celery-worker
    networks:
      - auth-bridge-network
    env_file:
      - .env
    command: uv run celery --app=src.core.celery.config:celery_app worker -l INFO 

networks:
  auth-bridge-network:
    external: true

